apiVersion: v1
kind: Pod
metadata:
  labels:
    app: maybe-finance
  name: maybe-finance
spec:
  containers:
    - name: app
      image: ghcr.io/maybe-finance/maybe:latest
      dependsOn:
        - name: postgres
      volumeMounts:
        - name: maybe-finance-appdata
          mountPath: /rails/storage
      ports:
        - containerPort: 3000
          hostPort: 3000
      envFrom:
        - configMapRef:
            name: maybe-finance-config
    - name: postgres
      image: docker.io/library/postgres:16
      volumeMounts:
        - name: maybe-finance-pgdata
          mountPath: /var/lib/postgresql/data
      envFrom:
        - configMapRef:
            name: maybe-finance-config

  volumes:
    - name: maybe-finance-pgdata
      persistentVolumeClaim:
        claimName: maybe-finance-pgdata
    - name: maybe-finance-appdata
      persistentVolumeClaim:
        claimName: maybe-finance-appdata
