auto_sync = false
dialect = "uk"
enter_accept = false
filter_mode = "global"
filter_mode_shell_up_key_binding = "global"
inline_height = 24
invert = false
search_mode = "fuzzy"
search_mode_shell_up_key_binding = "fuzzy"
show_help = true
show_preview = false
style = "full"
update_check = false
workspaces = false