ARG BASE_IMAGE=ghcr.io/rsturla/eternal-linux/main/silverblue
ARG BASE_TAG=38
ARG FEDORA_VERSION=${BASE_TAG}

FROM ${BASE_IMAGE}:${BASE_TAG}

COPY files/etc /etc
COPY files/usr /usr

# Install ublue-os GNOME Software
RUN wget https://copr.fedorainfracloud.org/coprs/ublue-os/gnome-software/repo/fedora-${FEDORA_VERSION}/ublue-os-gnome-software-fedora-${FEDORA_VERSION}.repo -O /etc/yum.repos.d/ublue-os-gnome-software.repo && \
  rpm-ostree override replace --experimental --from repo=copr:copr.fedorainfracloud.org:ublue-os:gnome-software \
    gnome-software \
    gnome-software-rpm-ostree \
  && \
  rm /etc/yum.repos.d/ublue-os-gnome-software.repo && \
  rm -rf /tmp/* /var/* && \
  ostree container commit

RUN rpm-ostree override remove \
    gnome-tour \
    gnome-terminal \
    gnome-terminal-nautilus \
  && \
  rm -rf /tmp/* /var/* && \
  ostree container commit

# Configure Just
RUN echo "!include /usr/share/eternal/lumina.just" >> /usr/share/eternal/justfile

RUN rpm-ostree install python3-pip && \
  pip install --prefix=/usr yafti && \
  rm -rf /tmp/* /var/* && \
  ostree container commit

RUN rpm-ostree install \
    gnome-shell-extension-appindicator \
    gnome-shell-extension-dash-to-dock \
    gnome-shell-extension-blur-my-shell \
    gnome-shell-extension-gsconnect \
    nautilus-gsconnect \
    yaru-theme \
    gnome-tweaks \
    gnome-console \
  && \
  rm -rf /tmp/* /var/* && \
  ostree container commit

# Configure dconf
RUN systemctl unmask dconf-update.service && \
  systemctl enable dconf-update.service \
  && \
  rm -rf /tmp/* /var/* && \
  ostree container commit

# Install virt-manager
RUN rpm-ostree install \
    libvirt \
    virt-manager \
  && \
  rm -rf /tmp/* /var/* && \
  ostree container commit

# Install LXC/LXD
RUN wget https://copr.fedorainfracloud.org/coprs/ganto/lxc4/repo/fedora-${FEDORA_VERSION}/ganto-lxc4-fedora-${FEDORA_VERSION}.repo -O /etc/yum.repos.d/ganto-lxc4.repo && \
  rpm-ostree install \
    lxc \
    lxd \
  && \
  rm /etc/yum.repos.d/ganto-lxc4.repo && \
  rm -rf /tmp/* /var/* && \
  ostree container commit
