ARG BASE_IMAGE=ghcr.io/rsturla/eternal-linux/main/silverblue
ARG BASE_TAG=38
ARG FEDORA_VERSION=${BASE_TAG}

FROM ${BASE_IMAGE}:${BASE_TAG}

COPY files/etc/yum.repos.d /etc/yum.repos.d
COPY files/usr /usr

# Configure Just
RUN echo "!include /usr/share/eternal/lumina.just" >> /usr/share/eternal/justfile && \
  echo "!include /usr/share/eternal/lumina-setup.just" >> /usr/share/eternal/justfile

# Install YAFTI and dependencies
RUN rpm-ostree install python3-pip && \
  pip install --prefix=/usr yafti \
  && \
  rm -rf /tmp/* /var/* && \
  ostree container commit

# Configure Gnome Shell Extensions and themes
RUN rpm-ostree install \
    gnome-shell-extension-appindicator \
    gnome-shell-extension-dash-to-dock \
    gnome-shell-extension-blur-my-shell \
    gnome-shell-extension-gsconnect \
    nautilus-gsconnect \
    yaru-theme \
    gnome-tweaks \
  && \
  rm -rf /tmp/* /var/* && \
  ostree container commit

# Configure dconf automated updates
RUN systemctl unmask dconf-update.service && \
  systemctl enable dconf-update.service \
  && \
  rm -rf /tmp/* /var/* && \
  ostree container commit

# Install Starship Shell Prompt
RUN curl -Lo /tmp/starship.tar.gz "https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz" && \
  tar -xzf /tmp/starship.tar.gz -C /tmp && \
  install -c -m 0755 /tmp/starship /usr/bin && \
  echo 'eval "$(starship init bash)"' >> /etc/bashrc \
  && \
  rm -rf /tmp/* /var/* && \
  ostree container commit

# Install Visual Studio Code
RUN rpm-ostree install \
    code \
  && \
  rm -f /etc/yum.repos.d/vscode.repo \
  && \
  rm -rf /tmp/* /var/* && \
  ostree container commit

# Install virt-manager
RUN rpm-ostree install \
    libvirt \
    virt-manager \
  && \
  rm -rf /tmp/* /var/* && \
  ostree container commit

# Install Docker
RUN rpm-ostree install \
  docker-ce \
  docker-ce-cli \
  containerd.io \
  docker-buildx-plugin \
  docker-compose-plugin \
  && \
  rm -f /etc/yum.repos.d/docker-ce.repo \
  && \
  systemctl enable docker.service \
  && \
  rm -rf /var/* /tmp/* && \
  ostree container commit

# Install DevPod
RUN wget https://github.com/loft-sh/devpod/releases/latest/download/DevPod_linux_x86_64.rpm -O /tmp/devpod.rpm && \
  rpm-ostree install /tmp/devpod.rpm && \
  wget https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-amd64 -O /tmp/devpod && \
  install -c -m 0755 /tmp/devpod /usr/bin \
  && \
  rm -rf /tmp/* /var/* && \
  ostree container commit

# Install additional CLI apps
COPY --from=cgr.dev/chainguard/ko:latest /usr/bin/ko /usr/bin/ko
COPY --from=cgr.dev/chainguard/kubectl:latest /usr/bin/kubectl /usr/bin/kubectl
RUN curl -Lo ./kind "https://github.com/kubernetes-sigs/kind/releases/latest/download/kind-$(uname)-amd64" && \
  chmod +x ./kind && \
  install -c -m 0755 ./kind /usr/bin/kind \
  && \
  rm -rf /tmp/* /var/* && \
  ostree container commit
