name: Generate Image SBOM

inputs:
  image-ref:
    description: 'The image reference to generate the SBOM for'
    required: false
    default: ''
  artifact-name:
    description: 'The name of the artifact to generate the SBOM for'
    required: false
  config-file:
    description: 'The path to the configuration file'
    required: false
  output-file:
    description: 'The path to the SBOM file'
    required: false
    default: 'syft-sbom.json'

outputs:
  output-file:
    description: 'The path to the SBOM file'
    value: ${{ inputs.output-file }}
  artifact-url:
    description: 'The URL to the uploaded artifact'
    value: ${{ steps.upload.outputs.artifact_url }}

runs:
  using: composite
  steps:
    - name: Install Syft
      shell: bash
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Scan Image
      if: inputs.image-ref != ''
      shell: bash
      env:
        SYFT_CONFIG: ${{ inputs.config-file != '' && inputs.config-file || format('{0}/syft.default.yaml', github.action_path) }}
      run: |
        syft ${{ inputs.image-ref }} \
          --output cyclonedx-json=${{ inputs.output-file }} \
          --config $SYFT_CONFIG

    - name: Upload SBOM Artifact
      if: inputs.artifact-name != ''
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.output-file }}
        if-no-files-found: error
        compression-level: 8
