[init]
	defaultBranch = main

[credential]
	helper = cache --timeout 21600
	helper = oauth

[url "https://github.com/"]
	insteadOf = git@github.com:

[url "https://gitlab.com/"]
  insteadOf = git@gitlab.com:
