name: Live ISO

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Maximize Build Space
        uses: ublue-os/remove-unwanted-software@cc0becac701cf642c8f0a6613bbdaf5dc36b259e # v9
        with:
          remove-codeql: true

      - name: Build ISO
        working-directory: ./installer
        run: ./build.sh

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: live-iso
          path: ./installer/.build/installer.iso
