name: Build Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 1,13 * * *" # 1am & 1pm every day
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-lumina:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fedora-version: [39]
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      IMAGE_NAME: eternal-linux/lumina
      BASE_IMAGE_NAME: eternal-linux/main/silverblue
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Optimize GHA Storage
        uses: rsturla/eternal-main/.github/actions/optimise-gha-storage@main

      - name: Verify Base Image
        uses: rsturla/eternal-main/.github/actions/verify-image@main
        with:
          image: '${{ env.IMAGE_REGISTRY }}/${{ env.BASE_IMAGE_NAME}}:${{ matrix.fedora-version }}-nvidia${{ matrix.nvidia-version }}'

      - name: Generate Image Tags
        uses: rsturla/eternal-main/.github/actions/generate-image-tags@main
        id: generate-image-tags
        with:
          image-name: ${{ env.IMAGE_REGISTRY}}/${{ env.IMAGE_NAME }}
          major-version: ${{ matrix.fedora-version }}
          is-release: ${{ github.event_name != 'pull_request' }}

      - name: Login to GHCR
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

      - name: Build Image
        id: build
        uses: redhat-actions/buildah-build@b4dc19b4ba891854660ab1f88a097d45aa158f76 # v2
        with:
          context: lumina/.
          containerfiles: |
            lumina/Containerfile
          image: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ steps.generate-image-tags.outputs.tags }}
          build-args: |
            BASE_TAG=${{ matrix.fedora-version }}

      - name: Push Image
        id: push
        uses: redhat-actions/push-to-registry@9986a6552bc4571882a4a67e016b17361412b4df # v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Sign Image
        uses: rsturla/eternal-main/.github/actions/sign-image@main
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          digest: ${{ steps.push.outputs.digest }}
          private-key: ${{ secrets.ETERNAL_LINUX_SIGNING_KEY }}
          private-key-passphrase: ${{ secrets.ETERNAL_LINUX_SIGNING_KEY_PASSPHRASE }}


  build-lumina-nvidia:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fedora-version: [39]
        nvidia-version: [545, 550]
        include:
          - nvidia-version: 545
            nvidia-is-stable: true
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      IMAGE_NAME: eternal-linux/lumina
      BASE_IMAGE_NAME: eternal-linux/main/silverblue
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Optimize GHA Storage
        uses: rsturla/eternal-main/.github/actions/optimise-gha-storage@main

      - name: Verify Base Image
        uses: rsturla/eternal-main/.github/actions/verify-image@main
        with:
          image: '${{ env.IMAGE_REGISTRY }}/${{ env.BASE_IMAGE_NAME}}:${{ matrix.fedora-version }}-nvidia${{ matrix.nvidia-version }}'

      - name: Generate Image Tags
        uses: rsturla/eternal-main/.github/actions/generate-image-tags@main
        id: generate-image-tags
        with:
          image-name: ${{ env.IMAGE_REGISTRY}}/${{ env.IMAGE_NAME }}
          major-version: ${{ matrix.fedora-version }}
          is-release: ${{ github.event_name != 'pull_request' }}
          nvidia-driver-version: ${{ matrix.nvidia-version }}
          nvidia-driver-is-stable: ${{ matrix.nvidia-is-stable }}

      - name: Build Image
        id: build
        uses: redhat-actions/buildah-build@b4dc19b4ba891854660ab1f88a097d45aa158f76 # v2
        with:
          context: lumina/.
          containerfiles: |
            lumina/Containerfile
          image: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ steps.generate-image-tags.outputs.tags }}
          build-args: |
            BASE_TAG=${{ matrix.fedora-version }}-nvidia${{ matrix.nvidia-version }}

      - name: Push Image
        id: push
        uses: redhat-actions/push-to-registry@9986a6552bc4571882a4a67e016b17361412b4df # v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Sign Image
        uses: rsturla/eternal-main/.github/actions/sign-image@main
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          digest: ${{ steps.push.outputs.digest }}
          private-key: ${{ secrets.ETERNAL_LINUX_SIGNING_KEY }}
          private-key-passphrase: ${{ secrets.ETERNAL_LINUX_SIGNING_KEY_PASSPHRASE }}

  check:
    needs: [build-lumina, build-lumina-nvidia]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Check Job Status
        uses: rsturla/eternal-main/.github/actions/check-jobs-success@main
        with:
          jobs: ${{ toJSON(needs) }}
