name: Cleanup old images

on:
  schedule:
    - cron: '0 0 * * *' # 12am every day
  workflow_dispatch:
  pull_request:

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [lumina]
    steps:
      - name: Delete untagged images
        uses: actions/delete-package-versions@0d39a63126868f5eefaa47169615edd3c0f61e20 # v4
        with:
          package-name: eternal-linux/${{ matrix.image }}
          package-type: container
          min-versions-to-keep: 10
          delete-only-untagged-versions: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for rate limit reset
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: { rateLimit: { resetAt } } } = await github.rest.rateLimit.get();
            const waitTime = resetAt - new Date();
            core.info(`Waiting ${waitTime}ms for rate limit reset`);
            await new Promise(resolve => setTimeout(resolve, waitTime));

      - name: Delete PR images
        uses: actions/delete-package-versions@0d39a63126868f5eefaa47169615edd3c0f61e20 # v4
        with:
          package-name: eternal-linux/${{ matrix.image }}
          package-type: container
          min-versions-to-keep: 50
          ignore-versions: '^(?!pr[0-9]{2}-).+$'
          token: ${{ secrets.GITHUB_TOKEN }}
